### ISSUE TITLE
Latest container image crashing

### ISSUE THREAD

**Issue by ddovidenko** [jertel/vuegraf#155]
Looks like when the latest image got pulled there's a missing module causing a crash:

```
Traceback (most recent call last):
  File "/opt/vuegraf/vuegraf.py", line 28, in <module>
    from pyemvue import PyEmVue
  File "/usr/local/lib/python3.12/site-packages/pyemvue/__init__.py", line 2, in <module>
    from pyemvue.pyemvue import PyEmVue
  File "/usr/local/lib/python3.12/site-packages/pyemvue/pyemvue.py", line 9, in <module>
    from pyemvue.auth import Auth
  File "/usr/local/lib/python3.12/site-packages/pyemvue/auth.py", line 3, in <module>
    from jose import jwt
ModuleNotFoundError: No module named 'jose'
```

**Comment by jertel** [comment]
Thanks for the heads-up. Latest info is here: https://github.com/magico13/PyEmVue/issues/62

**Comment by jertel** [comment]
The latest image is working again. I've manually pulled in pycognito while we wait for a new release of PyEmVue that removes that deprecated dependency.

**Comment by ddovidenko** [comment]
Confirmed working!

**Comment by jertel** [comment]
Vuegraf version 1.7.2 was released today with the upgraded PyEmVue library.
