### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by paulmataruso** [jertel/vuegraf#160]
Using a default install with docker-compose, and It ran successfully the first time. Stayed running for a little bit then the vuegraf container dumps out the error message below

`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 19 column 2 (char 560)
2024-04-05 03:15:26.958364+00:00 | INFO  | Starting Vuegraf version 1.7.2

Traceback (most recent call last):
  File "/opt/vuegraf/vuegraf.py", line 243, in <module>
    config = json.load(configFile)
             ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
`

Please let me know if you want any more logs or any of my config files

**Comment by paulmataruso** [comment]
Please disregard, it seems to be working just fine now after a docker compose down --force-recreate
