### ISSUE TITLE
latest image throwing 403 Client Error: Forbidden for url: https://api.emporiaenergy.com/cu...

### ISSUE THREAD

**Issue by dth202** [jertel/vuegraf#96]
I am seeing the following error when pulling jertel/vuegraf:latest image (updated 5 months ago) . rolling back to jertel/vuegraf:1.3.4 I don't have the error anymore.

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.emporiaenergy.com/customers/12134/devices?detailed=true&hierarchy=true
2022-07-06 16:00:31.457138 | INFO  | Login completed
Traceback (most recent call last):
  File "/opt/vuegraf/vuegraf.py", line 115, in <module>
    populateDevices(account)
  File "/opt/vuegraf/vuegraf.py", line 55, in populateDevices
    devices = account['vue'].get_devices()
  File "/usr/local/lib/python3.9/site-packages/pyemvue/pyemvue.py", line 39, in get_devices
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

**Comment by jertel** [comment]
I'm not aware of any changes, between 1.3.4 and the latest image, that would affect the login/device inquiry phase of the app. 

I tried to reproduce the error by removing my running container, pulling `jertel/vuegraf:latest` and launching a new container, however it continues to operate correctly. If you can isolate a config setting or code change that can help me reproduce it I will be better able to investigate it.
